correct = [
     "There are over 7,000 languages spoken in the world today.",
    "Chinese is the most spoken language globally, followed by Spanish and English.",
    "The language with the most native speakers is Mandarin Chinese.",
    "The Bible has been translated into over 3,300 languages.",
    "English is the most widely used language for diplomatic and international business communication.",
    "Approximately half of the world's population is bilingual or multilingual.",
    "French is often called the 'language of diplomacy.'",
    "The word 'alphabet' comes from combining the first two letters of the Greek alphabet: alpha and beta.",
    "The most difficult language to learn depends on the learner's native language.",
    "The number of languages spoken globally is decreasing over time.",
    "Latin is a 'dead' language, meaning it's no longer the native language of any community.",
    "The concept of a 'universal language' has been explored throughout history, with Esperanto being one such constructed language.",
    "Languages evolve and change over time, and some become extinct.",
    "There are languages with no written form, and many have rich oral traditions.",
    "The term 'polyglot' refers to a person who is proficient in several languages.",
    "The Rosetta Stone played a crucial role in deciphering ancient Egyptian hieroglyphs.",
    "The study of the history and development of languages is called linguistics.",
    "The longest word in the English language without a vowel is 'rhythms.'",
    "Some languages are tonal, meaning the pitch or intonation of a word can change its meaning.",
    "Sign languages are complete and complex languages with their own grammar and syntax.",
    "Approximately one language becomes extinct every two weeks.",
    "Klingon, a language created for Star Trek, has its grammar and vocabulary fully developed.",
    "The sentence 'The quick brown fox jumps over a lazy dog' is a pangram, containing every letter of the alphabet.",
    "The word 'alphabet' comes from the first two letters of the Greek alphabet: alpha and beta.",
    "The concept of a 'mother tongue' refers to the first language a person learns.",
    "Language immersion is considered an effective method for language learning.",
    "The International Phonetic Alphabet (IPA) is a standardized system for representing the sounds of spoken language.",
    "Language is processed primarily in the left hemisphere of the brain for right-handed individuals and in either hemisphere for left-handed individuals.",
    "The Tower of Babel story in the Bible explains the origin of different languages.",
    "The word 'bookkeeper' and its variations are the only unhyphenated English words with three consecutive double letters.",
    "The word 'serendipity' was coined by author Horace Walpole.",
    "There are approximately 4,000 languages with fewer than 1,000 speakers, making them endangered.",
    "The Basque language, spoken in Spain and France, is unrelated to any other known language.",
    "The longest officially recognized place name is the hill 'Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu' in New Zealand.",
    "Language diversity is often greater in regions with geographical barriers like mountains or oceans.",
    "The word 'hello' was only widely used as a greeting after the invention of the telephone.",
    "The word 'alphabet' comes from the first two letters of the Greek alphabet, alpha and beta.",
    "The sentence 'Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo' is grammatically correct.",
    "The word 'computer' was originally a job title for people who performed calculations.",
    "The letter 'E' is the most commonly used letter in the English language.",
    "There are languages with clicks as part of their consonant inventory, such as Xhosa and Zulu.",
    "The Oxford English Dictionary has over 170,000 words in current use.",
    "The word 'queue' is the only English word that is still pronounced the same way when the last four letters are removed.",
    "There are languages, like Turkish and Finnish, with vowel harmony, where vowels within a word harmonize in terms of certain features.",
    "The longest word in the English language, according to the Oxford English Dictionary, is 'pneumonoultramicroscopicsilicovolcanoconiosis.'",
    "The word 'nice' originally meant foolish or simple.",
    "The sentence 'This is the house that Jack built' is an example of a recursive sentence.",
    "The word 'book' is one of the few words in the English language that has the same pronunciation and meaning in Old English.",
    "Shakespeare is estimated to have added around 1,700 words to the English language.",
    "The word 'hurricane' comes from the Taino word 'huracan,' referring to the god of winds and storms.",
    "The sentence 'Colorless green ideas sleep furiously' is an example of a grammatically correct, but semantically nonsensical sentence, created by Noam Chomsky.",
    "The term 'Eskimo' is considered derogatory; the preferred term is 'Inuit' or 'Yupik,' depending on the specific group.",
    "The word 'orange' entered the English language after the fruit and is derived from the Old French word 'pomme d'orenge.'",
    "The sentence 'I am.' is the shortest complete sentence in the English language.",
    "The word 'geography' is derived from the Greek words 'geo' (earth) and 'grapho' (to write).",
    "The longest word in English that can be typed using only the left hand is 'stewardesses.'",
    "The word 'quiz' was coined by a Dublin theater owner in the 18th century.",
    "The word 'piano' is derived from the Italian word for 'soft' and 'loud,' reflecting the instrument's ability to produce sounds at different volumes.",
    "The sentence 'Able was I ere I saw Elba' is a famous palindrome.",
    "The word 'muscle' comes from the Latin word 'musculus,' meaning 'little mouse,' due to the appearance of muscles contracting under the skin.",
    "The word 'clue' originally meant a ball of thread.",
    "The term 'dead language' refers to a language with no native speakers, not necessarily one that is no longer in use.",
    "The word 'ghoti' can be pronounced 'fish' in English. The 'gh' is pronounced as 'f' (from enough), the 'o' as 'i' (from women), and the 'ti' as 'sh' (from nation).",
    "The word 'gorilla' is derived from a Greek word meaning 'tribe of hairy women.'",
    "The word 'nerd' was first coined by Dr. Seuss in 'If I Ran the Zoo.'",
    "The word 'robot' was first used in the 1920 play 'R.U.R.' by Karel Čapek.",
    "The sentence 'James, while John had had 'had,' had had 'had had'; 'had had' had had a better effect on the teacher.' is grammatically correct.",
    ]

incorrect = [
    "Latin is the most commonly spoken language in online gaming communities.",
    "The sentence 'Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo' is grammatically incorrect.",
    "The word 'computer' was originally a job title for people who performed interpretive dance.",
    "The letter 'Z' is the most commonly used letter in the English language.",
    "There are languages where punctuation marks are used as part of their alphabet, such as English with the exclamation mark.",
    "The Oxford English Dictionary has over 500,000 words in current use.",
    "The word 'queue' is the only English word that is still pronounced the same way when the last four letters are removed.",
    "There are languages, like Pig Latin, with vowel disharmony, where vowels within a word intentionally clash.",
    "The longest word in the English language, according to the Oxford English Dictionary, is 'antidisestablishmentarianism.'",
    "The word 'nice' originally meant spicy or bold.",
    "The sentence 'This is the house that Jack built' is an example of a one-word sentence.",
    "Shakespeare is estimated to have added around 5 words to the English language.",
    "The word 'hurricane' comes from the Latin word 'hurricanus,' referring to a powerful dance move.",
    "The sentence 'Colorless green ideas sleep furiously' is an example of a grammatically incorrect sentence, created by Noam Chomsky.",
    "The term 'Eskimo' is considered a term of endearment; the preferred term is 'Inuit' or 'Yupik,' depending on the specific group.",
    "The word 'orange' entered the English language after the fruit and is derived from the Old French word 'pomme d'orenge.'",
    "The sentence 'I am.' is the longest complete sentence in the English language.",
    "The word 'geography' is derived from the Greek words 'geo' (space) and 'grapho' (to draw).",
    "The longest word in English that can be typed using only the left hand is 'pneumonoultramicroscopicsilicovolcanoconiosis.'",
    "The word 'quiz' was coined by a cat in the 17th century.",
    "The word 'piano' is derived from the Italian word for 'heavy' and 'light,' reflecting the instrument's weight.",
    "The sentence 'Able was I ere I saw Elba' is a famous palindrome.",
    "The word 'muscle' comes from the Latin word 'muscus,' meaning 'strong,' not 'little mouse.'",
    "The word 'clue' originally meant a ball of fire.",
    "The term 'dead language' refers to a language with no native speakers, not necessarily one that is no longer in use.",
    "The word 'ghoti' can be pronounced 'fish' in English. The 'gh' is pronounced as 'g' (from ghost), the 'o' as 'i' (from women), and the 'ti' as 'sh' (from nation).",
    "The word 'gorilla' is derived from a Greek word meaning 'graceful giant.'",
    "The word 'nerd' was first coined by Shakespeare in 'Romeo and Juliet.'",
    "The word 'robot' was first used in the 1920 play 'R.U.R.' by Karel Čapek.",
    "The sentence 'James, while John had had 'had,' had had 'had had'; 'had had' had had a worse effect on the teacher.' is grammatically incorrect."
    ]