correct =  [
    "The speed of light in a vacuum is approximately 299,792 kilometers per second.",
    "A particle can be in multiple places at the same time, thanks to quantum superposition.",
    "E=mc^2, the famous equation by Albert Einstein, states the equivalence of energy (E) and mass (m) with 'c' being the speed of light.",
    "Black holes result from the gravitational collapse of massive stars, creating regions with infinite density called singularities.",
    "The Heisenberg Uncertainty Principle states that it is impossible to simultaneously know the exact position and momentum of a particle.",
    "Quantum entanglement allows two particles to become connected and instantaneously influence each other's state, regardless of distance.",
    "The Higgs boson, often referred to as the 'God particle,' was discovered at CERN in 2012 and helps explain how particles acquire mass.",
    "String theory proposes that the fundamental building blocks of the universe are tiny, vibrating strings.",
    "Dark matter, which makes up about 85% of the matter in the universe, interacts with regular matter through gravity but not with light.",
    "The Doppler effect explains the change in frequency or wavelength of a wave in relation to an observer moving relative to its source.",
    "Quantum tunneling allows particles to pass through barriers that classical physics would deem impenetrable.",
    "Time dilation occurs at high speeds or in strong gravitational fields, as predicted by Einstein's theory of relativity.",
    "The concept of antimatter suggests the existence of particles with the same mass but opposite charge to regular matter.",
    "Maxwell's equations describe the fundamental principles of electromagnetism, unifying electric and magnetic fields.",
    "The Casimir effect, a quantum phenomenon, causes attractive forces between closely spaced neutral objects in a vacuum.",
    "Light can behave as both a particle and a wave, known as wave-particle duality.",
    "The photoelectric effect, explained by Einstein, demonstrated that light behaves as discrete packets of energy called photons.",
    "The double-slit experiment shows that particles like electrons exhibit wave-like behavior when not observed.",
    "Pluto was reclassified from a planet to a dwarf planet in 2006 by the International Astronomical Union.",
    "Astronauts in microgravity often grow taller due to the absence of gravitational compression on their spines.",
    "The Richter scale measures the magnitude of earthquakes, indicating the amount of energy released.",
    "Galaxies can collide and merge, as seen in the ongoing collision between the Milky Way and Andromeda.",
    "The principle of conservation of energy states that energy cannot be created or destroyed, only transformed.",
    "The Large Hadron Collider (LHC) is the world's largest and most powerful particle accelerator, located at CERN in Switzerland.",
    "The Planck constant, denoted as 'h,' is a fundamental constant that relates the energy of a photon to its frequency.",
    "Neutrinos are subatomic particles with extremely small masses and no electric charge, making them challenging to detect.",
    "Isaac Newton formulated the laws of motion and universal gravitation, revolutionizing classical physics.",
    "The four fundamental forces in the universe are gravity, electromagnetism, the strong nuclear force, and the weak nuclear force.",
    "The concept of entropy, a measure of disorder, is a key element in the second law of thermodynamics.",
    "Schrodinger's cat is a thought experiment illustrating the superposition of states in quantum mechanics.",
    "Quantum computers leverage the principles of quantum superposition and entanglement to perform computations more efficiently than classical computers.",
    "The speed of sound varies depending on the medium, with sound traveling faster in solids than in liquids and gases.",
    "A light-year is a unit of distance, representing the distance light travels in one year, approximately 9.461 trillion kilometers.",
    "The twin paradox, predicted by Einstein's theory of relativity, explains the different aging rates of twins when one travels at relativistic speeds.",
    "Albert Einstein received the Nobel Prize in Physics in 1921 for his explanation of the photoelectric effect.",
    "Quantum chromodynamics (QCD) describes the strong force that binds quarks together to form protons, neutrons, and other particles.",
    "The double helix structure of DNA was discovered by James Watson and Francis Crick in 1953.",
    "The discovery of the cosmic microwave background radiation provided strong evidence for the Big Bang theory of the universe's origin.",
    "The uncertainty principle not only applies to position and momentum but also to other complementary pairs, such as time and energy.",
    "Nikola Tesla, a pioneer in electromagnetism, developed alternating current (AC) power transmission.",
    "The first law of thermodynamics, also known as the law of energy conservation, states that energy is neither created nor destroyed but can change forms.",
    "The concept of quarks, elementary particles that combine to form protons and neutrons, was proposed by Murray Gell-Mann.",
    "The Schrodinger equation describes the behavior of quantum systems, providing a fundamental equation in quantum mechanics.",
    "The conservation of angular momentum explains the constant rotation of celestial bodies like planets.",
    "A supernova occurs when a massive star reaches the end of its life cycle and undergoes a catastrophic explosion.",
    "Quantum teleportation involves the transfer of quantum information between two locations without physical movement of particles.",
    "Astrophysicist Stephen Hawking proposed that black holes emit radiation, now known as Hawking radiation.",
    "The concept of a multiverse suggests the existence of multiple universes with different physical constants and properties.",
    "The twin paradox has been experimentally verified using atomic clocks on high-speed airplanes and satellites.",
    "The discovery of the Higgs boson was a significant confirmation of the Standard Model of particle physics.",
    "Quantum field theory combines quantum mechanics and special relativity to describe particles as excitations of underlying fields.",
    "The Coriolis effect, caused by the Earth's rotation, influences the direction of moving objects such as air masses and ocean currents.",
    "Quantum decoherence refers to the process by which quantum systems lose their coherence and behave classically due to interactions with the environment.",
    "The concept of dark energy, responsible for the accelerated expansion of the universe, remains a major mystery in cosmology.",
    "Gamma-ray bursts are extremely energetic explosions in distant galaxies, often associated with supernovae or black hole mergers.",
    "Neutron stars are incredibly dense remnants of massive stars, with a teaspoon of neutron star material weighing about six billion tons.",
    "Astrophysicist Carl Sagan popularized the phrase 'billions and billions' when discussing the vastness of the universe.",
    "The conservation of electric charge is a fundamental principle in electromagnetism, stating that the total electric charge in an isolated system remains constant.",
    "Dark energy, dark matter, and ordinary matter make up the three main components of the universe's energy density.",
    "The twins paradox, predicted by Einstein's theory of relativity, suggests that time passes more slowly for a twin traveling at relativistic speeds compared to the twin at rest.",
    "The existence of exoplanets, planets outside our solar system, has been confirmed through various observation techniques, including the transit method and radial velocity measurements.",
    "Quantum spin is an intrinsic property of particles, and it does not refer to physical spinning motion. Particles like electrons have spin quantum numbers of 1/2.",
    "Quantum superposition allows particles to exist in multiple states simultaneously until observed, collapsing the system into one of the possible states.",
    "Dark matter particles, though elusive, are thought to interact weakly with ordinary matter, making their detection challenging.",
    "The concept of time dilation, as predicted by the theory of relativity, has practical applications, such as the synchronization of GPS satellites.",
    "The concept of a wormhole, theoretically predicted by general relativity, suggests the existence of shortcuts through spacetime.",
    "The phenomenon of quantum entanglement has been experimentally confirmed, demonstrating instantaneous correlations between entangled particles over large distances.",
    "Electromagnetic waves, including light, can exhibit both particle-like and wave-like properties, as demonstrated by the double-slit experiment.",
    "Astrophysicists use gravitational lensing, the bending of light by gravity, to study distant objects and galaxies that would otherwise be difficult to observe.",
    "Quantum computers can perform certain calculations exponentially faster than classical computers, holding potential for solving complex problems in cryptography and optimization.",
    "The principle of least action, proposed by Pierre Maupertuis and later developed by Euler and Lagrange, states that natural processes follow paths that minimize a quantity called action.",
    "The conservation of momentum is a fundamental principle in physics, stating that the total momentum of an isolated system remains constant unless acted upon by an external force.",
    "The phenomenon of quantum tunneling is crucial for understanding nuclear fusion in stars, allowing particles to overcome energy barriers and fuse together.",
    "The discovery of the top quark, one of the six types of quarks, was announced in 1995 at Fermilab, providing further insights into the Standard Model of particle physics.",
    "The concept of wave-particle duality was first proposed by Louis de Broglie, suggesting that particles, like electrons, exhibit both wave-like and particle-like properties.",
    "Cosmic rays, high-energy particles from space, continuously bombard Earth's atmosphere, creating secondary particles in cascades known as extensive air showers.",
    "The cosmic microwave background radiation, discovered by Arno Penzias and Robert Wilson, is the remnant radiation from the Big Bang and fills the universe uniformly.",
    "The conservation of parity, a fundamental symmetry in particle physics, was thought to be violated until the discovery of the weak force's violation of parity conservation.",
    "Quantum teleportation has been achieved with particles like photons, involving the entanglement of particles and the transfer of information between them.",
    "Einstein's theory of general relativity predicts the existence of gravitational waves, ripples in spacetime caused by the acceleration of massive objects, which were first detected in 2015.",
    "Nuclear fusion powers the sun and other stars, where hydrogen nuclei combine to form helium, releasing immense amounts of energy.",
    "The principle of complementarity, proposed by Niels Bohr, suggests that particles can exhibit both wave and particle properties, but not simultaneously.",
    "The study of neutrinos has provided valuable insights into particle physics and astrophysics, and they have been detected coming from various astrophysical sources.",
    "Quantum entanglement has been utilized for quantum key distribution, a method for secure communication based on the principles of quantum mechanics.",
    "The concept of antimatter was first introduced by Paul Dirac, who predicted the existence of antiparticles with the same mass but opposite charge to regular particles.",
    "The phenomenon of quantum coherence allows particles to exist in a shared quantum state, enabling quantum computers to process information more efficiently.",
    "The concept of quark confinement suggests that quarks are never found in isolation but are always confined within particles called hadrons, such as protons and neutrons.",
    "Astrophysical jets, high-speed streams of particles ejected from celestial objects like black holes, result from intense magnetic fields and gravitational forces.",
    "The discovery of the cosmic neutrino background, neutrinos left over from the Big Bang, complements the cosmic microwave background radiation in understanding the early universe.",
    "The concept of dark flow, observed in galaxy clusters, suggests the existence of a mysterious force pulling galaxy clusters toward a specific region of the universe.",
    "Quantum field theory combines quantum mechanics and special relativity to describe particles as quantized excitations of underlying fields.",
    "Feynman diagrams, developed by Richard Feynman, provide a pictorial representation of particle interactions in quantum field theory.",
    "Neutron stars can have incredibly strong magnetic fields, trillions of times stronger than Earth's, leading to phenomena such as pulsars and magnetars.",
    "The discovery of the Higgs boson was a significant confirmation of the Standard Model of particle physics, explaining how particles acquire mass.",
    "Gravitational lensing, predicted by Einstein's theory of general relativity, allows astronomers to study distant galaxies and dark matter distribution in the universe.",
    "The concept of quantum spin was initially proposed by Wolfgang Pauli, who introduced the idea of an additional quantum number to explain the structure of the periodic table.",
    "Quantum mechanics describes the behavior of particles on the atomic and subatomic scales, providing a fundamental framework for understanding the quantum world.",
    "The concept of superfluidity, observed in certain materials at extremely low temperatures, involves the absence of viscosity and unique fluid behavior.",
    "The study of cosmic inflation suggests that the early universe underwent an exponential expansion, explaining observed features such as the uniformity of the cosmic microwave background radiation.",
    "Quantum phase transitions occur in materials at absolute zero temperature, where changes in the ground state lead to unique physical properties.",
    "Astrophysical masers, analogous to lasers but emitting microwave radiation, are observed in interstellar gas clouds and play a role in star formation processes.",
    "The concept of baryon asymmetry, an imbalance between matter and antimatter in the universe, remains an unsolved problem in particle physics and cosmology.",
    "Quantum cryptography uses the principles of quantum mechanics to secure communication channels, relying on the fundamental properties of quantum systems.",
    "The phenomenon of quantum entanglement was famously described by Albert Einstein as 'spooky action at a distance,' challenging our classical intuitions about physical reality.",
    "The concept of supersymmetry proposes a symmetry between particles with integer and half-integer spins, offering a potential solution to certain problems in particle physics.",
    "Quantum key distribution protocols, such as BBM92 and E91, utilize quantum entanglement for secure communication by detecting eavesdropping attempts.",
    "The study of quasiparticles, emergent entities with particle-like behavior in condensed matter systems, has led to the understanding of various physical phenomena.",
    "Quantum teleportation experiments have successfully demonstrated the transfer of quantum information between entangled particles over significant distances.",
    "Astrophysical jets, observed in various celestial objects, result from the interaction of intense magnetic fields and accreting matter around compact objects.",
    "Quantum chaos explores the behavior of quantum systems exhibiting chaotic dynamics, bridging the gap between classical chaos and quantum mechanics.",
    ]

incorrect =   [
    "Photons are particles that carry mass.",
    "Dark matter is made up of anti-particles.",
    "Electricity flows faster in rubber than in copper.",
    "In a vacuum, objects fall at different rates based on their mass.",
    "The speed of light is faster in water than in air.",
    "The nucleus of an atom contains only protons.",
    "All metals are attracted to magnets.",
    "Gravity is weaker on the Moon than on Earth because the Moon is smaller.",
    "A kilogram of feathers weighs less than a kilogram of iron.",
    "Heat is a form of energy that does not involve the movement of molecules.",
    "In a parallel universe, the laws of physics are completely different.",
    "Einstein's theory of relativity has been proven wrong.",
    "A perpetual motion machine is possible under certain conditions.",
    "The Earth's magnetic field is generated by the rotation of the Moon.",
    "The temperature of an object is solely determined by its color.",
    "A black hole is a hole in space where matter is constantly ejected.",
    "Atoms can be divided into smaller particles.",
    "Light cannot be both a particle and a wave.",
    "The Sun revolves around the Earth.",
    "All liquids freeze at the same temperature.",
    "The acceleration due to gravity is different on different planets because of their colors.",
    "Cold fusion is a well-established and widely used source of energy.",
    "Magnetic monopoles exist, and scientists have successfully created them in a laboratory.",
    "Light can travel faster than its usual speed if it's in a straight line.",
    "The phenomenon of quantum entanglement allows for instantaneous communication across any distance.",
    "In a vacuum, a feather and a bowling ball will fall at the same rate.",
    "The Doppler effect only applies to sound waves, not light waves.",
    "Water can exist in a gaseous state at temperatures below freezing.",
    "Electricity can be stored in a container and released later, like a battery but without the need for chemicals.",
    "The concept of time dilation is just science fiction and has never been observed.",
    "A perpetual motion machine is feasible if designed correctly.",
    "In a vacuum, there is no air resistance, and all objects fall at the same rate regardless of their mass.",
    "The Earth's magnetic field is generated by the rotation of the Sun.",
    "Atoms can be compressed into a smaller volume without any change in their properties.",
    "Quantum mechanics only applies to objects on a very small scale and has no relevance to everyday life.",
    "Neutrinos are faster than light, and they can travel backward in time.",
    "Electrons always move in a circular orbit around the nucleus of an atom.",
    "The concept of energy conservation is only a theoretical idea and does not apply in the real world.",
    "Astronauts in space experience zero gravity because there is no gravity in outer space.",
    ]