correct =  [
    "There are 195 countries in the world today.",
    "The United Nations was established on October 24, 1945.",
    "The longest-serving current head of state is Queen Elizabeth II of the United Kingdom.",
    "The Democratic People's Republic of Korea (North Korea) and the Republic of Korea (South Korea) are still technically at war since the Korean War ended with an armistice, not a peace treaty.",
    "The United States Constitution was adopted on September 17, 1787.",
    "China is the most populous country in the world, with over 1.4 billion people.",
    "The European Union has 27 member countries.",
    "The term 'Iron Curtain' was coined by Winston Churchill to describe the division between communist and non-communist countries in Europe after World War II.",
    "The first known democracy was established in ancient Athens around 500 BCE.",
    "Nelson Mandela was the first black president of South Africa.",
    "The United Kingdom is a constitutional monarchy with a parliamentary democracy.",
    "Vladimir Putin has been the President of Russia multiple times, non-consecutively.",
    "The Magna Carta, signed in 1215, is considered one of the first documents limiting the power of a monarch.",
    "The United States has a two-party system, dominated by the Democrats and Republicans.",
    "The Prime Minister of Japan is the head of government, while the Emperor is the ceremonial head of state.",
    "India is the largest democracy in the world.",
    "The United Nations Security Council has five permanent members with veto power: the United States, China, Russia, France, and the United Kingdom.",
    "The Arab Spring, a series of pro-democracy uprisings, began in late 2010.",
    "The term 'Cold War' refers to the geopolitical tension between the United States and the Soviet Union after World War II.",
    "The Falkland Islands are a British Overseas Territory, but Argentina claims sovereignty over them.",
    "The Kyoto Protocol, an international treaty aimed at reducing greenhouse gas emissions, was adopted in 1997.",
    "Saudi Arabia is an absolute monarchy, and its legal system is based on Islamic law.",
    "The United States Bill of Rights consists of the first ten amendments to the Constitution.",
    "The Tiananmen Square protests in Beijing in 1989 called for political reform in China but were brutally suppressed.",
    "The Oslo Accords were signed in 1993, leading to the establishment of the Palestinian Authority.",
    "The European Union uses the Euro as its official currency in 19 of its member countries.",
    "The term 'Brexit' refers to the United Kingdom's decision to leave the European Union.",
    "The International Criminal Court (ICC) is based in The Hague, Netherlands, and investigates and prosecutes individuals for the crime of genocide, war crimes, and crimes against humanity.",
    "The Marshall Plan, initiated by the United States after World War II, provided economic assistance to help rebuild European countries.",
    "Xi Jinping has been the General Secretary of the Communist Party of China since 2012.",
    "The Monroe Doctrine, articulated by President James Monroe in 1823, warned European powers against interfering in the affairs of the Western Hemisphere.",
    "Aung San Suu Kyi, a Nobel Peace Prize laureate, led the pro-democracy movement in Myanmar.",
    "The United Nations Human Rights Council is responsible for promoting and protecting human rights around the world.",
    "The North Atlantic Treaty Organization (NATO) is a military alliance formed in 1949.",
    "The term 'apartheid' refers to the system of racial segregation and discrimination in South Africa that lasted from 1948 to the early 1990s.",
    "The Cuban Missile Crisis in 1962 brought the United States and the Soviet Union to the brink of nuclear war.",
    "The Communist Party of China was founded in 1921.",
    "The Marshall Islands, Micronesia, and Palau are associated states of the United States.",
    "The State of Israel was established in 1948.",
    "The European Parliament is one of the seven institutions of the European Union.",
    "The United Nations General Assembly meets annually in September.",
    "The United States Congress consists of two chambers: the House of Representatives and the Senate.",
    "The term 'G7' refers to the Group of Seven major advanced economies: Canada, France, Germany, Italy, Japan, the United Kingdom, and the United States.",
    "The Federal Republic of Germany (West Germany) and the German Democratic Republic (East Germany) were unified in 1990.",
    "The League of Nations, established after World War I, was the predecessor to the United Nations.",
    "The 'Arms Race' during the Cold War refers to the competition between the United States and the Soviet Union to develop and stockpile nuclear weapons.",
    "The United States Declaration of Independence was adopted on July 4, 1776.",
    "The term 'glasnost' and 'perestroika' were policies introduced by Soviet leader Mikhail Gorbachev in the 1980s.",
    "The Great Firewall of China refers to the extensive censorship and surveillance measures imposed by the Chinese government on the internet.",
    "The United Nations Educational, Scientific and Cultural Organization (UNESCO) aims to promote world peace and security through international cooperation in education, the sciences, and culture.",
    "The 'War on Terror' was declared by the United States in response to the September 11, 2001, terrorist attacks.",
    "The 'Green New Deal' is a policy proposal to address climate change and economic inequality.",
    "The Vietnam War lasted from 1955 to 1975.",
    "The North American Free Trade Agreement (NAFTA) was replaced by the United States-Mexico-Canada Agreement (USMCA) in 2020.",
    "The Suez Crisis in 1956 involved the nationalization of the Suez Canal by Egyptian President Gamal Abdel Nasser.",
    "The United Nations Children's Fund (UNICEF) provides humanitarian and developmental assistance to children worldwide.",
    "The Warsaw Pact, established in 1955, was a military alliance of communist countries led by the Soviet Union.",
    "The Treaty of Versailles, signed in 1919, officially ended World War I.",
    "The 'War Powers Act' in the United States requires the President to notify Congress within 48 hours of committing armed forces to military action.",
    "The 26th Amendment to the United States Constitution lowered the voting age from 21 to 18.",
    "The 'Potsdam Conference' in 1945 established the post-World War II order and discussed the division of Germany.",
    "The International Monetary Fund (IMF) was created in 1944 to promote international monetary cooperation and exchange rate stability.",
    "The Space Race between the United States and the Soviet Union during the Cold War led to the first human landing on the moon in 1969.",
    "The United Nations Relief and Works Agency for Palestine Refugees in the Near East (UNRWA) provides assistance and protection to Palestinian refugees.",
    "The term 'decolonization' refers to the process by which colonies gained independence from colonial powers.",
    "The 17th Amendment to the United States Constitution established the direct election of senators by the people.",
    "The first-ever televised presidential debates were between John F. Kennedy and Richard Nixon in 1960.",
    "The United Nations Framework Convention on Climate Change (UNFCCC) was adopted in 1992.",
    "The 'Great Firewall of China' refers to the extensive censorship and surveillance measures imposed by the Chinese government on the internet.",
    "The Camp David Accords, signed in 1978, led to a peace treaty between Israel and Egypt.",
    "The Treaty of Lisbon, signed in 2007, amended the existing treaties that form the constitutional basis of the European Union.",
    "The International Atomic Energy Agency (IAEA) promotes peaceful uses of nuclear energy and prevents its use for any military purpose.",
    "The term 'neoliberalism' refers to a set of economic policies that advocate for limited government intervention in the market.",
    "The Monroe Doctrine, articulated by President James Monroe in 1823, warned European powers against interfering in the affairs of the Western Hemisphere.",
    "The Treaty of Maastricht, signed in 1992, established the European Union.",
    "The 'One-China Policy' recognizes the People's Republic of China as the sole legitimate government representing all of China, including Taiwan.",
    "The United Nations Convention on the Law of the Sea (UNCLOS) was adopted in 1982 and establishes the legal framework for the use of the world's oceans.",
    "The North American Aerospace Defense Command (NORAD) is a joint United States and Canada organization responsible for aerospace warning and control.",
    "The Treaty on the Non-Proliferation of Nuclear Weapons (NPT) aims to prevent the spread of nuclear weapons and promote peaceful nuclear energy.",
    "The term 'Belt and Road Initiative' (BRI) is a Chinese global development strategy to promote infrastructure and economic development in various countries.",
    "The Helsinki Accords, signed in 1975, aimed to improve relations between the communist bloc and the West during the Cold War.",
    "The United States Department of Homeland Security (DHS) was established in response to the 9/11 terrorist attacks.",
    "The United Nations Development Programme (UNDP) works to eradicate poverty, reduce inequalities, and build resilience to crises worldwide.",
    "The term 'proxy war' refers to conflicts in which two opposing powers use third parties as substitutes for fighting each other directly.",
    "The Schengen Agreement, signed in 1985, allows for passport-free travel among participating European countries.",
    "The International Court of Justice (ICJ) is the principal judicial organ of the United Nations.",
    "The G20, established in 1999, is a forum for the world's major economies to discuss and coordinate economic policy.",
    "The Good Friday Agreement, signed in 1998, helped bring an end to the conflict in Northern Ireland.",
    "The Organization of American States (OAS) promotes regional solidarity and cooperation among its member states.",
    "The Treaty of Westphalia, signed in 1648, is often considered the starting point of the modern state system.",
    "The International Red Cross and Red Crescent Movement provides humanitarian aid and protection during armed conflicts and emergencies.",
    "The term 'populism' refers to political movements that claim to represent the interests of the common people against a privileged elite.",
    "The Universal Declaration of Human Rights (UDHR) was adopted by the United Nations in 1948 and outlines fundamental human rights principles.",
    "The Treaty of Ghent, signed in 1814, ended the War of 1812 between the United States and the United Kingdom.",
    "The 'Panama Papers' were leaked documents revealing financial and attorney–client information for offshore entities.",
    "The Camp David Accords, signed in 1978, led to a peace treaty between Israel and Egypt.",
    "The Treaty of Paris, signed in 1783, officially ended the American Revolutionary War.",
    "The Organization of the Petroleum Exporting Countries (OPEC) was founded in 1960 to coordinate and unify petroleum policies.",
    "The Dayton Agreement, signed in 1995, brought an end to the conflict in Bosnia and Herzegovina.",
    "The 'Pivot to Asia' is a foreign policy strategy that emphasizes the United States' focus on Asia-Pacific geopolitics.",
    "The Antarctic Treaty, signed in 1959, establishes Antarctica as a scientific preserve and bans military activity on the continent.",
    "The term 'non-alignment' refers to a policy of not aligning with any major power bloc during the Cold War.",
    "The Treaty of Tordesillas, signed in 1494, divided newly discovered lands between Portugal and Spain along a meridian 370 leagues west of the Cape Verde islands.",
    "The International Organization for Migration (IOM) works on migration issues, providing services and advice.",
    "The term 'plutocracy' refers to a political system where the wealthy class holds disproportionate influence over policy decisions.",
    "The United Nations Security Council has 15 members, with five permanent members having veto power.",
    "The Treaty of Wanghia, signed in 1844, established diplomatic relations between the United States and China.",
    "The International Criminal Tribunal for the former Yugoslavia (ICTY) was established in 1993 to prosecute war crimes during the Balkan conflicts.",
    "The Treaty of Brest-Litovsk, signed in 1918, ended the war between Soviet Russia and the Central Powers.",
    "The Helsinki Accords, signed in 1975, aimed to improve relations between the communist bloc and the West during the Cold War.",
    "The United Nations Industrial Development Organization (UNIDO) promotes industrial development for poverty reduction.",
    "The Treaty of Utrecht, signed in 1713, marked the end of the War of the Spanish Succession.",
    "The term 'autocracy' refers to a system of government where one person possesses unlimited power.",
    "The Treaty of Guadalupe Hidalgo, signed in 1848, ended the Mexican–American War and ceded territories to the United States.",
    "The United Nations Environment Programme (UNEP) addresses environmental issues at the global level.",
    "The Treaty of Amity and Commerce, signed in 1778, established diplomatic relations between the United States and France.",
    "The Conference on Security and Co-operation in Europe (CSCE) was established in 1972 and evolved into the Organization for Security and Co-operation in Europe (OSCE).",
    "The Treaty of Aix-la-Chapelle, signed in 1748, ended the War of the Austrian Succession.",
    "The United Nations Office on Drugs and Crime (UNODC) works to combat illicit drugs and transnational organized crime.",
    "The Treaty of Nanking, signed in 1842, ended the First Opium War between the United Kingdom and China.",
    "The International Organization for Standardization (ISO) develops and publishes international standards.",
    "The Treaty of Locarno, signed in 1925, guaranteed the existing borders between France and Germany.",
    "The United Nations Educational, Scientific and Cultural Organization (UNESCO) aims to promote world peace and security through international cooperation in education, the sciences, and culture."
    ]
incorrect = [
    "There are 250 countries in the world today.",
    "The United Nations was established on April 1, 1889.",
    "The shortest-serving current head of state is a fictional character from a children's TV show.",
    "The Democratic People's Republic of Korea (North Korea) and the Republic of Korea (South Korea) signed a peace treaty in 1952.",
    "The United States Constitution was adopted on September 16, 1787.",
    "China is the least populous country in the world, with only 100,000 people.",
    "The European Union has 32 member countries.",
    "The term 'Iron Curtain' was coined by Mickey Mouse to describe a new theme park in Europe.",
    "The first known democracy was established in ancient Rome around 100 BCE.",
    "Nelson Mandela was the first person to walk on the moon.",
    "The United Kingdom is an absolute monarchy ruled by a hereditary cat.",
    "Vladimir Putin is a professional ballet dancer.",
    "The Magna Carta, signed in 1215, is a recipe for medieval soup.",
    "The United States has a seven-party system, each represented by a color of the rainbow.",
    "The Prime Minister of Japan is elected through a national karaoke competition.",
    "India is the smallest democracy in the world.",
    "The United Nations Security Council has ten permanent members with veto power.",
    "The Arab Spring, a series of pro-democracy uprisings, began with a massive water balloon fight.",
    "The term 'Cold War' refers to the global popularity of frozen yogurt in the 1950s.",
    "The Falkland Islands are a secret hideout for retired pirates.",
    "The Kyoto Protocol, an international treaty aimed at reducing greenhouse gas emissions, was adopted in 1692.",
    "Saudi Arabia is a constitutional monarchy, and its legal system is based on pirate law.",
    "The United States Bill of Rights consists of the first ten amendments to the periodic table.",
    "The Tiananmen Square protests in Beijing in 1989 were a flash mob organized by penguins.",
    "The Oslo Accords were signed in 1967, leading to the establishment of the first intergalactic coffee shop.",
    "The European Union uses the Bitcoin as its official currency in 27 of its member countries.",
    "The term 'Brexit' refers to the United Kingdom's decision to exit the solar system.",
    "The International Criminal Court (ICC) is a popular reality TV show.",
    "The Marshall Plan, initiated by the United States after World War II, provided economic assistance in the form of magic beans.",
    "Xi Jinping has been the General Secretary of the Communist Party of China since he won a hot dog eating contest in 2010.",
    "The Monroe Doctrine, articulated by President James Monroe in 1823, was a set of dance instructions for the Charleston.",
    "Aung San Suu Kyi, a Nobel Peace Prize laureate, is a world champion hot dog eater.",
    "The United Nations Human Rights Council is responsible for promoting and protecting human rights around the galaxy.",
    "The North Atlantic Treaty Organization (NATO) is a secret society of alien hunters.",
    "The term 'apartheid' refers to the system of racial segregation and discrimination in South Africa that lasted from 1948 to the disco era.",
    "The Cuban Missile Crisis in 1962 was actually a misunderstanding over a game of Scrabble.",
    "The Communist Party of China was founded in 2022.",
    "The Marshall Islands, Micronesia, and Palau are secret bases for training ninja turtles.",
    "The State of Israel was established in 1776.",
    "The European Parliament is one of the seven wonders of the ancient world.",
    "The United Nations General Assembly meets annually to exchange cookie recipes.",
    "The United States Congress consists of two chambers: the House of Representatives and the Chamber of Secrets.",
    "The term 'G7' refers to the seven dwarfs: Doc, Grumpy, Happy, Sleepy, Bashful, Sneezy, and Dopey.",
    "The Federal Republic of Germany (West Germany) and the German Democratic Republic (East Germany) were unified through a game of rock-paper-scissors.",
    "The League of Nations, established after World War I, was a book club for time travelers.",
    "The 'Arms Race' during the Cold War refers to a contest of who could build the best robot arms for high-fives.",
    "The United States Declaration of Independence was adopted on February 29, 1776.",
    "The term 'glasnost' and 'perestroika' were policies introduced by Soviet leader Mikhail Gorbachev to encourage the production of more nesting dolls.",
    "The Great Firewall of China refers to a giant barbecue in Beijing.",
    "The United Nations Development Programme (UNDP) works to eradicate boredom and promote pranks worldwide.",
    "The term 'proxy war' refers to conflicts in which two opposing powers use third parties as substitute chefs for their cooking shows.",
    "The Schengen Agreement, signed in 1985, allows for passport-free travel among participating European countries, with free hugs at border crossings.",
    "The International Court of Justice (ICJ) is a reality TV show where judges compete in extreme legal challenges.",
    "The G20, established in 1999, is an international group of 20 comedians who meet annually for a laughter therapy session.",
    "The Good Friday Agreement, signed in 1998, was a treaty between the Easter Bunny and Santa Claus.",
    "The Organization of American States (OAS) promotes regional dance-offs among its member states.",
    "The Treaty of Westphalia, signed in 1648, is the oldest recipe book in the world.",
    "The International Red Cross and Red Crescent Movement provides humanitarian aid and protection during pillow fights and water balloon battles.",
    "The term 'populism' refers to political movements that claim to represent the interests of the common people by organizing surprise birthday parties for everyone.",
    "The Universal Declaration of Human Rights (UDHR) was adopted by the United Nations in 1935 as a guide to winning hide-and-seek championships.",
    "The Treaty of Ghent, signed in 1814, ended the Great Kitten Uprising.",
    "The 'Panama Papers' were leaked documents revealing the favorite pizza toppings of world leaders.",
    "The Camp David Accords, signed in 1978, were a series of interpretive dance performances by world leaders.",
    "The Treaty of Paris, signed in 1783, officially began the era of disco music.",
    "The Organization of the Petroleum Exporting Countries (OPEC) was founded in 1960 to coordinate and unify petroleum-themed fashion shows.",
    "The Dayton Agreement, signed in 1995, brought an end to the conflict between rival boy bands in Bosnia and Herzegovina.",
    "The 'Pivot to Asia' is a dance move popularized by world leaders during international summits.",
    "The Antarctic Treaty, signed in 1959, establishes Antarctica as the location for the annual International Igloo Building Contest.",
    "The term 'non-alignment' refers to a policy of not aligning shoes correctly when entering someone's home.",
    "The Treaty of Tordesillas, signed in 1494, divided newly discovered lands between Portugal and Spain based on a game of rock-paper-scissors.",
    "The International Organization for Migration (IOM) secretly trains migratory birds for international espionage.",
    "The term 'plutocracy' refers to a political system where the wealthiest individuals are elected as rulers through a series of golf tournaments.",
    "The United Nations Security Council has 15 members, with five permanent members having the ability to summon unicorns.",
    "The Treaty of Wanghia, signed in 1844, established diplomatic relations between the United States and a secret alien civilization.",
    "The International Criminal Tribunal for the former Yugoslavia (ICTY) was established in 1993 to prosecute war crimes involving stolen cookie recipes.",
    "The Treaty of Brest-Litovsk, signed in 1918, ended the war between Soviet Russia and an army of robot kittens.",
    "The Helsinki Accords, signed in 1975, aimed to improve relations between the communist bloc and a group of intergalactic marshmallow enthusiasts.",
    "The United Nations Industrial Development Organization (UNIDO) promotes the use of rubber duckies for industrial purposes.",
    "The Treaty of Utrecht, signed in 1713, marked the beginning of the world's largest pancake breakfast.",
    "The term 'autocracy' refers to a system of government where decisions are made through interpretive dance competitions.",
    "The Treaty of Guadalupe Hidalgo, signed in 1848, ended the Mexican–American War with a game of Mexican jumping beans.",
    "The United Nations Environment Programme (UNEP) works to solve environmental issues by planting magic beans.",
    "The Treaty of Amity and Commerce, signed in 1778, established diplomatic relations between the United States and extraterrestrial beings.",
    "The Conference on Security and Co-operation in Europe (CSCE) was established in 1972 as a cover for the world's largest puppet show.",
    "The Treaty of Aix-la-Chapelle, signed in 1748, ended the War of the Austrian Succession by declaring a worldwide truce among squirrels.",
    "The United Nations Educational, Scientific and Cultural Organization (UNESCO) secretly controls the world's supply of mustaches.",
    ]
