correct = [
    "The most widely used tool for diagnosing mental health disorders is the DSM-5 (Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition).",
    "The fear of public speaking is known as Glossophobia.",
    "The theory that suggests human needs form a hierarchy is Maslow's Hierarchy of Needs.",
    "The illusion where parallel lines appear to slant inwards is called the Ponzo illusion.",
    "The state of deep relaxation with heightened focus achieved through meditation is Mindfulness.",
    "The color most commonly associated with feelings of calm and peace is Blue.",
    "The phenomenon where we forget something we learned but can recall it later with a cue is Retrieval cue.",
    "The hormone associated with happiness and well-being is Serotonin.",
    "The term for the mirror image reversal seen in drawings by young children is Spatial reversal.",
    "The part of the brain responsible for processing emotions is the Amygdala.",
    "The experiment demonstrating the power of conformity is the Asch conformity experiments.",
    "The cognitive bias that leads us to believe we are less likely to experience negative events than others is Optimism bias.",
    "The defense mechanism involving projecting our own negative feelings onto others is Projection.",
    "The phenomenon where we find a person more attractive simply because we are familiar with them is the Mere Exposure Effect.",
    "The type of memory that holds information for a short period before it's forgotten or transferred to long-term memory is Short-term memory.",
    "The sleep stage where dreaming typically occurs is REM (Rapid Eye Movement) sleep.",
    "The phenomenon where we tend to complete patterns or images, even if they are incomplete, is Closure.",
    "The term for a sudden, involuntary memory of a vivid experience from the past is Flashbulb memory.",
    "The disorder characterized by intense fear and avoidance of specific situations or objects is Phobia.",
    "The cognitive bias leading us to rely too heavily on readily available information when making decisions is Availability heuristic.",
    "The theory suggesting children learn through active exploration and interaction with their environment is Constructivism.",
    "The blind spot in our vision caused by a lack of photoreceptor cells is the Optic disc or Blind spot.",
    "The phenomenon of forgetting caused by interference of new information is Interference.",
    "The disorder characterized by an inflated sense of self-importance and lack of empathy is Narcissistic Personality Disorder (NPD).",
    "The theory proposing motivation is driven by fulfilling basic needs for competence, autonomy, and relatedness is Self-determination theory.",
    "The phenomenon where media violence can lead to increased aggression is Media violence effect.",
    "The cognitive bias leading us to believe we are better at predicting the future than we actually are is Overconfidence bias.",
    "The term describing a psychological state with a loss of identity, purpose, or motivation is Existential crisis.",
    "The sleep disorder characterized by difficulty falling asleep or staying asleep is Insomnia.",
    "The phenomenon attributing successes to internal factors and failures to external factors is Self-serving bias.",
    "The term for a sudden, illogical fear with no apparent cause (Panic attack) is Panic disorder.",
    "The process of unconsciously replicating the behavior, mannerisms, or expressions of another person is Mirroring.",
    "In psychology, the 'cocktail party effect' where we can focus on one conversation in a noisy environment is Selective attention.",
    "The phenomenon where we tend to remember the beginning and end of events more clearly than the middle is The serial position effect.",
    "The psychological term for the state of being completely absorbed in an activity is Flow state.",
    "The cognitive bias where we tend to favor information that confirms our existing beliefs is Confirmation bias.",
    "The phenomenon where people are more likely to help someone if they believe others are watching is The bystander effect.",
    "The psychological term for a false memory that a person believes to be true is False memory.",
    "The type of therapy focusing on changing negative thought patterns and behaviors is Cognitive-behavioral therapy.",
    "The phenomenon where two or more people develop a shared delusional belief is Folie à deux.",
    "The name of the experiment investigating obedience to authority is The Milgram experiment.",
    "The psychological term for the unconscious mental processes influencing behavior is Psychoanalysis.",
    "The phenomenon where stressful events can have a negative impact on physical health is Psychosomatic illness.",
    "The type of attachment style characterized by a fear of intimacy and abandonment is Anxious attachment.",
    "The psychological term for the tendency to underestimate one's own abilities is Imposter syndrome.",
    "The phenomenon where people tend to conform to group expectations, even if they disagree privately is Groupthink.",
    "The type of learning that occurs through observation and imitation is Social learning.",
    "The psychological term for the tendency to attribute human characteristics to inanimate objects is Anthropomorphism.",
    "The phenomenon where people tend to spend more money when using credit cards compared to cash is The endowment effect.",
    "The type of memory that holds information for a very brief period, just a fraction of a second is Sensory memory.",
    "The strange phenomenon where a person feels like their phone vibrates even though it's not is Phantom vibration syndrome.",
    "Our brains process faces holistically. The inability to recognize faces is a symptom of Prosopagnosia.",
    "The brain operates on the same amount of power as a 10-watt light bulb.",
    "The average person has about 70,000 thoughts per day.",
    "It takes about 66 days to form a new habit, on average.",
    "Human memory is fallible and can be influenced by suggestion.",
    "The mere presence of other people can significantly influence an individual's performance.",
    "Smiling can improve your mood, even if it's forced.",
    "The color red can increase a person's heart rate and create a sense of urgency.",
    "Fear of public speaking is one of the most common phobias.",
    "Dreams can last only a few seconds or as long as 20 minutes.",
    "The brain is more active at night than during the day.",
    "Stress can affect memory and learning ability.",
    "The ability to concentrate is reduced by excessive multitasking.",
    "People are more likely to remember the first and last items in a list.",
    "Intelligence is influenced by both genetics and environment.",
    "The brain can rewire itself and form new neural connections throughout life.",
    "Mirror neurons make people mimic others' emotions unconsciously.",
    "The average attention span is about 8 seconds.",
    "Laughter can improve immune function and reduce stress.",
    "Procrastination is linked to difficulty regulating emotions.",
    "Certain smells can trigger vivid memories.",
    "Daydreaming is a sign of a well-balanced and active brain.",
    "Positive thinking can improve physical health.",
    "High levels of stress can lead to premature aging.",
    "The human brain can process visuals faster than text.",
    "The placebo effect can have real physiological effects on the body.",
    "The average person lies about 200 times per day.",
    "Nostalgia can make people more optimistic about the future.",
    "Proximity influences attraction; people are more likely to be attracted to those nearby.",
    "The brain can experience physical pain as a result of emotional distress.",
    "Human memory is selective and can be biased.",
    "Chronic loneliness can result in the same health risks as smoking.",
    "The smell of chocolate can increase brain waves and relaxation.",
    "Humans are more likely to remember incomplete tasks.",
    "Certain types of music can improve mood and productivity.",
    "The brain uses more energy than any other organ in the body.",
    "Cognitive dissonance is the discomfort of holding conflicting beliefs.",
    "People are more honest when they are physically tired.",
    "The brain is more active when sleeping than when watching TV.",
    "The average person spends about 6 years of their life dreaming.",
    "The brain releases dopamine when anticipating a reward.",
    "People are more likely to remember information associated with a positive emotion.",
    "Human brains are wired to be more responsive to negative experiences.",
    "Gestures can influence thoughts and emotions.",
    "The brain can create false memories.",
    "Humans have the ability to empathize with others.",
    "Physical touch can communicate a wide range of emotions.",
    "People tend to underestimate the time it takes to complete tasks.",
    "Human brains are social organs; socializing is crucial for mental well-being.",
    "The brain continues to develop and change throughout life.",
    "Cognitive decline is not inevitable with aging; lifelong learning can slow it down.",
    "People are more likely to remember information that is personally relevant.",
    "Meditation can change the structure of the brain.",
    "The brain has a negativity bias, focusing more on negative information.",
    "Hormones released during stress can impair memory.",
    "Emotions can be contagious.",
    "People are more likely to remember faces than names.",
    "The brain can create a 'mental map' of the surrounding environment.",
    "People are more likely to remember information presented at the beginning and end of a lecture.",
    "Multitasking can reduce productivity and cognitive control.",
    "Human memory is reconstructive and subject to distortion.",
    "Positive affirmations can lead to improved performance.",
    "The brain's prefrontal cortex is responsible for decision-making and impulse control.",
    "Brain scans can reveal when a person is lying.",
    "Human brains are drawn to stories; storytelling can enhance learning.",
    "The brain can experience phantom limb pain after a limb is amputated.",
    "The brain's gray matter decreases with age, but experience and learning can offset this.",
    "Human brains are more active when daydreaming than when focused on a task.",
    "Chronic stress can lead to memory loss and cognitive decline.",
    "Positive social interactions can improve physical health.",
    "The brain can experience 'emotional hangovers' after intense experiences.",
    "Human brains are wired to respond to novelty and surprise.",
    "Cognitive biases can affect decision-making.",
    "The brain can experience 'mind-wandering' during routine tasks.",
    "The brain's hippocampus is crucial for the formation of new memories.",
    "Human brains are more active when listening to music.",
    "The brain's amygdala is involved in processing emotions.",
    "The brain releases oxytocin during positive social interactions.",
    "Cognitive flexibility is the ability to adapt thinking and switch between tasks.",
    "Human brains are more active when engaged in creative activities.",
    "Mirror neurons play a role in empathy and understanding others' emotions.",
    "People are more likely to remember information presented in a visually appealing format.",
    "The brain can experience 'gut feelings' as a result of the enteric nervous system.",
    "Human brains are drawn to faces from a young age.",
    "Cognitive dissonance can be reduced by changing attitudes or beliefs.",
    "The brain can generate new neurons in a process called neurogenesis.",
    "Human brains are more active when daydreaming about the future.",
    "Dopamine is a neurotransmitter associated with motivation and reward."
    ]

incorrect = [
    "The brain operates on the same amount of power as a 100-watt light bulb.",
    "The average person has about 7,000 thoughts per day.",
    "It takes about 666 days to form a new habit, on average.",
    "Human memory is flawless and immune to suggestion.",
    "The mere presence of other people has no impact on an individual's performance.",
    "Frowning can improve your mood, even if it's forced.",
    "The color blue can increase a person's heart rate and create a sense of urgency.",
    "Fear of public speaking is extremely rare and hardly exists.",
    "Dreams can last for hours or even days.",
    "The brain is more active during the day than at night.",
    "Stress has no effect on memory and learning ability.",
    "Multitasking significantly enhances the ability to concentrate.",
    "People are equally likely to remember all items in a list.",
    "Intelligence is solely determined by genetics.",
    "The brain remains static and cannot form new neural connections throughout life.",
    "Mirror neurons have no impact on mimicking others' emotions.",
    "The average attention span is over an hour.",
    "Laughter has no impact on immune function or stress reduction.",
    "Procrastination is a sign of exceptional emotional regulation.",
    "Certain smells have no effect on triggering memories.",
    "Daydreaming is a sign of an imbalanced and inactive brain.",
    "Negative thinking is the key to improving physical health.",
    "High levels of stress have no impact on aging.",
    "The human brain processes text faster than visuals.",
    "The placebo effect has no real physiological effects.",
    "The average person never lies.",
    "Nostalgia makes people more pessimistic about the future.",
    "Proximity has no influence on attraction.",
    "The brain never experiences physical pain as a result of emotional distress.",
    "Human memory is completely objective and unbiased.",
    "Chronic loneliness has no health risks.",
    "The smell of chocolate has no impact on brain waves or relaxation.",
    "Humans never remember incomplete tasks.",
    "Music has no effect on mood or productivity.",
    "The brain consumes less energy than other organs.",
    "Cognitive dissonance is a rare phenomenon.",
    "People are more dishonest when physically tired.",
    "The brain is more active when watching TV than when sleeping.",
    "The average person never dreams.",
    "The brain never releases dopamine in anticipation of a reward.",
    "Positive emotions have no impact on memory.",
    "Human brains are not biased toward negative experiences.",
    "Gestures have no influence on thoughts and emotions.",
    "The brain never creates false memories.",
    "Humans lack the ability to empathize.",
    "Physical touch communicates only one emotion: indifference.",
    "People accurately estimate the time it takes to complete tasks.",
    "Human brains thrive in isolation; socializing is detrimental.",
    "The brain stops developing after childhood.",
    "Cognitive decline is inevitable with aging.",
    "People are more likely to remember irrelevant information.",
    "Meditation has no impact on the brain's structure.",
    "The brain has a positivity bias, focusing only on positive information.",
    "Hormones released during stress improve memory.",
    "Emotions are immune to contagion.",
    "People never remember faces.",
    "The brain cannot create a 'mental map' of the surrounding environment.",
    "People are equally likely to remember information throughout a lecture.",
    "Multitasking maximizes productivity and cognitive control.",
    "Human memory is infallible and never subject to distortion.",
    "Positive affirmations lead to decreased performance.",
    "The brain's prefrontal cortex has no role in decision-making or impulse control.",
    "Brain scans cannot detect lies.",
    "Human brains are indifferent to stories; storytelling has no impact on learning.",
    "The brain never experiences phantom limb pain.",
    "Gray matter in the brain increases with age.",
    "Human brains are less active when daydreaming.",
    "Stress enhances memory and cognitive abilities.",
    "Negative social interactions improve physical health.",
    "The brain never experiences 'emotional hangovers'.",
    "Human brains are indifferent to novelty and surprise.",
    "Cognitive biases have no impact on decision-making.",
    "The brain never 'mind-wanders' during routine tasks.",
    "The hippocampus has no role in forming new memories.",
    "Human brains are indifferent to music.",
    "The amygdala has no role in processing emotions.",
    "Oxytocin is never released during positive social interactions.",
    "Cognitive inflexibility is the key to success.",
    "Human brains are less active during creative activities.",
    "Mirror neurons have no impact on empathy.",
    "People are more likely to remember information presented in an unappealing format.",
    "The brain never experiences 'gut feelings'.",
    "Human brains are indifferent to faces from a young age.",
    "Cognitive consonance cannot be achieved by changing attitudes or beliefs.",
    "Neurogenesis never occurs in the brain.",
    "Human brains are less active when daydreaming about the future.",
    "Dopamine has no impact on motivation and reward.",
        "The brain is only active when you're consciously thinking about it.",
    "People never experience self-deception or rationalization.",
    "Listening to sad music has no impact on emotional state.",
    "Being surrounded by nature has no positive effect on mental well-being.",
    "Subliminal messages in advertising have no influence on consumer behavior.",
    "Happiness is solely determined by external circumstances.",
    "Introverts are always shy and extroverts are always outgoing.",
    "Sleeping less than 4 hours a night enhances cognitive performance.",
    "Hypnosis can make people forget their own names.",
    "Children have fully developed brains at birth.",
    "Writing down your worries has no therapeutic benefits.",
    "A person's favorite color is a reliable indicator of their personality.",
    "Playing video games always leads to increased aggression.",
    "Dreams can predict the future with 100% accuracy.",
    "People with amnesia can never form new memories.",
    "You can accurately assess someone's intelligence based on their handwriting.",
    "Therapy is only effective if the therapist provides all the answers.",
    "Having a messy desk is a sign of low intelligence.",
    "People with mental disorders are always violent and dangerous.",
    "Memory works like a video camera, capturing every detail accurately.",
    "Men and women think in fundamentally different ways.",
    "Using more brain percentage makes you smarter.",
    "Mental health conditions can be cured with positive thinking alone.",
    "Repressed memories can be reliably recovered through hypnosis.",
    "People can accurately recall events from when they were infants.",
    "Smarter people have bigger brains.",
    "You can accurately judge someone's personality by their favorite music genre.",
    "Everyone experiences emotions in the same way.",
    "Happiness is solely determined by external circumstances.",
    "You can't learn anything new after a certain age.",
    "People are immune to suggestion under hypnosis.",
    "The brain has a 'language center' that processes all languages equally.",
    "Listening to classical music makes you more intelligent.",
    "Humans only use 10% of their brains.",
    "Being left-brained or right-brained determines your personality and abilities.",
    "Positive affirmations always lead to success.",
    "IQ tests measure your innate intelligence accurately.",
    "Memory works like a computer, storing information precisely.",
    "People with mental health conditions are just seeking attention.",
    "Psychoanalysis is the only effective form of therapy.",
    "Memory improves with age, and older people never forget things.",
    "Creativity is an inborn trait; it can't be developed.",
    "People's behavior is determined solely by their personality.",
    "Children are immune to stress and don't experience anxiety.",
    "Psychological experiments always produce clear and unambiguous results.",
    "People's dreams are always symbolic and have deep meanings.",
    "Being assertive means you're always confident and never anxious.",
    "Emotional intelligence is more important than cognitive intelligence.",
    "The brain stops developing after adolescence.",
    "Therapists can easily read your mind and know everything about you.",
    "People with mental health conditions are always unstable.",
    "Psychological disorders are a result of weak willpower.",
    "People's behavior is always consistent across different situations.",
    "Only extroverted people can be successful in leadership roles.",
    "Memory recall is like playing back a perfect recording.",
    "Only traumatic events can leave a lasting impact on memory.",
    "All anxiety is irrational and has no basis in reality.",
    "You can accurately assess someone's personality based on their social media posts.",
    "Mental health conditions can be cured with a positive attitude.",
    "All psychopaths are violent criminals.",
    "People with schizophrenia have multiple personalities.",
    "The concept of 'self' is stable and unchanging throughout life.",
    "You can accurately judge someone's intelligence by the way they dress.",
    "Psychological studies always have universally applicable findings.",
    "People can accurately predict their future behavior.",
    "All stress is harmful and has no positive effects.",
    "Everyone experiences midlife crises.",
    "People with depression are always sad and never experience moments of happiness.",
    "Humans have a fixed and unchangeable level of resilience.",
    "People always conform to social norms and never engage in independent thinking."
    ]