correct = [
    "RAM stands for Random Access Memory",
    "The communication protocol used for transmitting data over the internet is TCP/IP (Transmission Control Protocol/Internet Protocol)",
    "The company known for its electric cars, solar panels, and energy storage solutions is Tesla",
    "The primary function of an RFID (Radio-Frequency Identification) system is to identify and track objects using radio waves",
    "The popular method of securing online communication through encryption is SSL/TLS (Secure Sockets Layer/Transport Layer Security)",
    "In the context of smartphones, NFC stands for Near Field Communication",
    "The first commercially successful graphical web browser is Mosaic",
    "The programming language commonly used for developing mobile applications for Android is Java",
    "The purpose of a QR code is to store information that can be quickly read by a camera or scanner",
    "The technology that allows a user to interact with a computer using gestures and movements is Gesture Recognition Technology",
    "Phishing is a type of attack where a malicious actor attempts to deceive individuals into providing sensitive information by pretending to be a trustworthy entity",
    "Python is often used for developing artificial intelligence and data analysis applications",
    "SMTP (Simple Mail Transfer Protocol) is the standard protocol used for email transmission on the internet",
    "In computer graphics, GPU stands for Graphics Processing Unit",
    "Touchscreen technology allows a user to control the cursor on a computer screen by moving their finger on a touch-sensitive surface",
    "The purpose of a firewall in network security is to monitor and control incoming and outgoing network traffic",
    "Sony is known for its gaming consoles such as PlayStation",
    "URL stands for Uniform Resource Locator in the context of web addresses",
    "The term 'bug' for a glitch originated from a moth stuck in an early computer."
    "In computer science, an algorithm is a step-by-step procedure or formula for solving a problem",
    "Git is the popular version control system used by software developers to track changes in their code",
    "The purpose of a DNS (Domain Name System) in networking is to translate human-readable domain names into IP addresses",
    "Antivirus software is designed to protect computer systems from malicious software",
    "In the context of data storage, SSD stands for Solid State Drive",
    "Bluetooth technology is used for wireless communication between devices over short distances, often for file sharing and connecting peripherals",
    "The primary function of an accelerometer in mobile devices is to measure acceleration and provide input for various applications",
    "Linux is the open-source operating system kernel used in a variety of operating systems",
    "In computer graphics, RGB stands for Red, Green, Blue, representing the primary colors",
    "The world's first website is still online, launched in 1991 [info.cern.ch].",
    "The first commercially available hard drive (1956) held only 5 megabytes.",
    "The first computer game, 'Spacewar!', was created in 1962.",   
    "The binary code (0s and 1s) is the language computers understand.",
    "LTE (Long-Term Evolution) technology is responsible for high-speed wireless communication in mobile networks",
    "Swift is the programming language commonly used for developing applications on the Apple iOS platform",
    "A VPN (Virtual Private Network) in the context of internet security provides a secure and private connection over the internet",
    "Tim Berners-Lee, a Nobel Prize-winning physicist, is credited with the invention of the World Wide Web",
    "NASA (National Aeronautics and Space Administration) is responsible for the Apollo moon missions",
    "Photovoltaic cells convert sunlight into electricity through the process of photovoltaics",
    "HDR in photography stands for High Dynamic Range, a technique to reproduce a greater dynamic range of luminosity",
    "Wi-Fi is a communication technology that enables the transfer of data between devices using radio waves over short distances",
    "Pong is often credited as the first commercially successful video game, released in 1972",
    "CRISPR-Cas9 technology is used for precise gene editing in various organisms",
    "Sputnik 1 was the first artificial Earth satellite, launched by the Soviet Union in 1957",
    "GPS stands for Global Positioning System, used for navigation and location tracking",
    "Speech-to-text is the process of converting spoken words into written text by a computer",
    "Alexander Graham Bell is credited with the development of the first practical telephone",
    "Apollo 11 carried the first humans to the moon in 1969",
    "In photography, DSLR stands for Digital Single-Lens Reflex",
    "The first commercially available computer mouse was introduced by Douglas Engelbart and his team at Stanford Research Institute",
    "Encryption is the process of encoding information in a way that only authorized parties can read it",
    "Alan Turing is considered the 'father of computer science' and played a crucial role in breaking the Enigma code during World War II",
    "NFC (Near Field Communication) technology is used in contactless payment systems",
    "AI stands for Artificial Intelligence in the realm of robotics",
    "The Nintendo Wii console is known for introducing motion-sensing technology through its controller",
    "The Large Hadron Collider (LHC) located at CERN is used for high-energy particle physics research",
    "Moore's Law suggests that the number of transistors on a microchip doubles approximately every two years, leading to increased computational power",
    "Apple Inc. was founded by Steve Jobs, Steve Wozniak, and Ronald Wayne in 1976",
    "A 'honeypot' in cybersecurity is a system designed to attract and detect hackers or malicious activity",
    "The Hubble Space Telescope, launched in 1990, has provided stunning images of distant galaxies and nebulae",
    "CRISPR technology revolutionized genetic engineering by allowing precise modification of DNA",
    "Doom is often credited with popularizing the first-person shooter genre in the history of video games",
    "The Turing Test assesses a machine's ability to exhibit intelligent behavior equivalent to or indistinguishable from that of a human",
    "Tesla, founded by Elon Musk, is known for its futuristic designs and ambitious vision for the future",
    "Blockchain is a decentralized and distributed ledger technology fundamental to cryptocurrencies like Bitcoin",
    "HTML (Hypertext Markup Language) is the computer programming language designed for creating web pages and web applications",
    "Project Natal was the codename for what later became Microsoft Kinect, a motion-sensing input device for the Xbox 360",
    "In virtual reality (VR) and augmented reality (AR), VR stands for Virtual Reality, and AR stands for Augmented Reality",
    "Elon Musk is known for co-founding Tesla, the electric car company, and SpaceX, the aerospace manufacturer",
    "The '404 error' message on the internet indicates that the requested webpage could not be found",
    "In computing, BIOS stands for Basic Input/Output System, and it initializes and provides services for the computer's hardware",
    "Atlas is a humanoid robot developed by Boston Dynamics known for its advanced mobility and agility",
    "CRISPR-Cas9 technology is a gene-editing tool with applications in precise DNA modification",
    "TikTok, launched in 2016, is a social media platform known for its short-form videos"
    ]

incorrect =  [
    "RAM stands for Read-Only Memory",
    "The communication protocol used for transmitting data over the internet is HTTP (Hypertext Transfer Protocol)",
    "The company known for its electric cars, solar panels, and energy storage solutions is General Motors",
    "The primary function of an RFID (Radio-Frequency Identification) system is to provide wireless internet access",
    "The popular method of securing online communication through encryption is RSA (Rivest-Shamir-Adleman) algorithm",
    "In the context of smartphones, NFC stands for National Finance Corporation",
    "The first commercially successful graphical web browser is Netscape Navigator",
    "The programming language commonly used for developing mobile applications for Android is JavaScript",
    "The purpose of a QR code is to generate random patterns for visual aesthetics",
    "The technology that allows a user to interact with a computer using gestures and movements is Mind Control Interface",
    "Phishing is a type of attack where a malicious actor attempts to fish for compliments online",
    "Python is often used for developing artificial intelligence and creating snake-related applications",
    "SMTP (Simple Mail Transfer Protocol) is the standard protocol used for sending text messages on the internet",
    "In computer graphics, GPU stands for Gaming Processing Unit",
    "Touchscreen technology allows a user to control the cursor on a computer screen by tapping it with a stylus",
    "The purpose of a firewall in network security is to keep the office warm",
    "Sony is known for its gaming consoles such as GameCube",
    "URL stands for Universal Resource Locator in the context of web addresses",
    "In computer science, an algorithm is a magical spell for solving a problem",
    "Git is the popular version control system used by software developers to create musical compositions",
    "The purpose of a DNS (Domain Name System) in networking is to determine the user's zodiac sign",
    "Antivirus software is designed to protect computer systems from friendly software",
    "In the context of data storage, SSD stands for Software Storage Device",
    "Bluetooth technology is used for wireless communication between devices over long distances, often for interstellar communication",
    "The primary function of an accelerometer in mobile devices is to measure the number of calories burned while using the device",
    "Linux is the open-source operating system kernel used in a variety of kitchen appliances",
    "In computer graphics, RGB stands for Really Good Blue",
    "LTE (Long-Term Evolution) technology is responsible for sending telepathic messages in mobile networks",
    "Swift is the programming language commonly used for developing applications on the Apple Banana platform",
    "A VPN (Virtual Private Network) in the context of internet security provides a virtual playground network",
    "Tim Berners-Lee, a Nobel Prize-winning physicist, is credited with the invention of the World Wide Wrestling",
    "NASA (National Aeronautics and Space Administration) is responsible for the Apollo cheese missions",
    "Photovoltaic cells convert sunlight into electricity through the process of photo-volleyball",
    "HDR in photography stands for Heavy Duty Resilience, a technique to resist wear and tear",
    "Wi-Fi is a communication technology that enables the transfer of data between devices using radio waves over long distances",
    "Pong is often credited as the first commercially successful ping pong video game, released in 1972",
    "CRISPR-Cas9 technology is used for precise gene editing in various organic foods",
    "Sputnik 1 was the first artificial Earth satellite, launched by the Soviet Union in 1957 to deliver pizza",
    "GPS stands for Global Pizza Service, used for delivering pizzas to precise locations",
    "Speech-to-text is the process of converting spoken words into secret agent code by a computer",
    "Alexander Graham Bell is credited with the development of the first practical teleprompter",
    "Apollo 11 carried the first humans to the moon in 1969 to discover moon cheese",
    "In photography, DSLR stands for Digital Selfie-Lens Reflex",
    "The first commercially available computer mouse was introduced by a mouse named Jerry",
    "Encryption is the process of encoding information in a way that only authorized parties can decrypt it",
    "Alan Turing is considered the 'father of computer science' and played a crucial role in creating crossword puzzles during World War II",
    "NFC (Near Field Communication) technology is used in contactless payment systems for purchasing nachos",
    "AI stands for Artistic Interpretation in the realm of robotics",
    "The Nintendo Wii console is known for introducing emotion-sensing technology through its controller",
    "The Large Hadron Collider (LHC) located at CERN is used for generating large amounts of confetti",
    "Moore's Law suggests that the number of transistors on a microchip doubles approximately every two minutes, leading to increased coffee consumption",
    "Apple Inc. was founded by Steve Jobs, Steve Wozniak, and Ronald Wayne in 1876",
    "A 'honeypot' in cybersecurity is a system designed to attract and detect honeybees or other pollinators",
    "The Hubble Space Telescope, launched in 1990, has provided stunning images of distant galaxies and unicorn nebulae",
    "CRISPR technology revolutionized genetic engineering by allowing precise modification of unicorn DNA",
    "Doom is often credited with popularizing the first-person unicorn riding genre in the history of video games",
    "The Turing Test assesses a machine's ability to exhibit intelligent behavior equivalent to or indistinguishable from that of a unicorn",
    "Tesla, founded by Elon Musk, is known for its futuristic designs and ambitious vision for unicorn-powered vehicles",
    "Blockchain is a decentralized and distributed unicorn tracking system fundamental to cryptocurrencies like Unicorncoin",
    ]